const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '..');
const mime = {'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'};
const server = http.createServer((req, res) => {
  const file = path.resolve(root, '.' + decodeURIComponent(new URL(req.url,'http://localhost').pathname));
  if (!file.startsWith(root + path.sep) || !fs.existsSync(file) || !fs.statSync(file).isFile()) {res.writeHead(404);res.end();return;}
  res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});
  fs.createReadStream(file).pipe(res);
});
(async()=>{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  const browser = await chromium.launch({headless:true,...(process.env.MTOOLS_BROWSER?{executablePath:process.env.MTOOLS_BROWSER}:{})});
  const page = await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  try {
    await page.goto(`http://127.0.0.1:${server.address().port}/preview/${process.env.MTOOLS_OFFLINE_PREVIEW?'MTools-Preview.html':'index.html'}`);
    await page.locator('.workflow-card').first().waitFor();
    assert.equal(await page.locator('.workflow-card').count(),6);
    assert.equal(await page.locator('.art-label').count(),0);
    await page.locator('[data-export]').first().click();
    assert.equal(await page.locator('[data-destination]').isVisible(),false);
    const exported=page.waitForEvent('download');
    await page.getByRole('button',{name:'Export',exact:true}).click();
    assert.match((await exported).suggestedFilename(),/\.json$/);
    await page.waitForTimeout(250);
if(process.env.MTOOLS_SCREENSHOTS) await page.screenshot({path:path.join(process.env.MTOOLS_SCREENSHOTS,'MTools-Workflows.png')});
    await page.locator('.card-main').first().click();
    await page.getByText('editorial-light.safetensors',{exact:true}).waitFor();
    assert.match(await page.locator('.check-result').innerText(),/missing/i);
    await page.locator('[data-action=open]').click();
    await page.getByText('Preview only. In ComfyUI this creates a new tab, preserving the current graph.',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Edit details',exact:true}).click();
    await page.getByLabel('Title',{exact:true}).fill('<img src=x onerror=alert(1)>');
    await page.getByRole('button',{name:'Save changes',exact:true}).click();
    await page.locator('.card-title').filter({hasText:'<img src=x onerror=alert(1)>'}).waitFor();
    assert.equal(await page.locator('.card-title img').count(),0);
    await page.getByRole('button',{name:'Reports',exact:true}).click();
    await page.locator('.folder').first().waitFor();
    assert.equal(await page.locator('.folder').count(),27);
    assert(await page.locator('.empty-folder[aria-disabled=true]').count()>0);
    await page.getByText('unet',{exact:true}).click();
    await page.getByText('flux1-dev.safetensors',{exact:true}).waitFor();
    if(process.env.MTOOLS_SCREENSHOTS) await page.screenshot({path:path.join(process.env.MTOOLS_SCREENSHOTS,'MTools-Reports.png')});
    await page.getByRole('button',{name:'Gallery',exact:true}).click();
    await page.locator('.media-card').first().waitFor();
    assert.equal(await page.locator('.media-card').count(),12);
    if(process.env.MTOOLS_SCREENSHOTS) await page.screenshot({path:path.join(process.env.MTOOLS_SCREENSHOTS,'MTools-Gallery.png')});
    await page.locator('[data-file-check]').first().check();
    await page.getByRole('button',{name:'Back up selected',exact:true}).click();
    await page.getByRole('button',{name:'Choose destination…'}).click();
    await page.locator('[data-folder]').first().click();
    await page.getByRole('button',{name:'Use this folder',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#app').shadowRoot.querySelector('input[name=destination]').value.includes('MTools-preview'));
    await page.getByRole('button',{name:'Export',exact:true}).click();
    await page.locator('.notice').filter({hasText:'Completed'}).waitFor();
    assert.equal(await page.locator('.job').isVisible(),false);
    await page.locator('[data-delete-media]').first().click();
    await page.getByRole('button',{name:'Delete permanently',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#app').shadowRoot.querySelectorAll('.media-card').length===11);
    await page.getByRole('button',{name:'Recovery bin',exact:true}).click();

    await page.getByText('The recovery bin is empty.',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Close dialog',exact:true}).click();
    await page.getByRole('button',{name:'Settings',exact:true}).click();
    await page.getByRole('button',{name:'Review full uninstall',exact:true}).click();
    await page.getByText(/not yet uninstalled/).waitFor();
    await page.getByRole('button',{name:'Close dialog',exact:true}).click();
    await page.setViewportSize({width:390,height:844});
    await page.reload();
    await page.locator('.workflow-card').first().waitFor();
    await page.locator('.card-main').first().click();
    await page.getByText('editorial-light.safetensors',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Workflows',exact:true}).click();
    await page.locator('.workflow-card').first().waitFor();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.waitForTimeout(250);
    if(process.env.MTOOLS_SCREENSHOTS) await page.screenshot({path:path.join(process.env.MTOOLS_SCREENSHOTS,'MTools-Mobile.png')});
    assert.deepEqual(errors,[]);
    console.log('UI PASS: library, details, missing model, XSS escaping, 27 categories, gallery selection/recovery, uninstall state, mobile layout; no page errors.');
  } finally {await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
